-- 变更原因：为已创建的第一版 RBAC 表和字段补充中文注释，便于通过 DBHub 等工具理解数据库结构。
-- 影响范围：仅修改 tenants、employees、departments、roles、menus、employee_roles、role_menus 的表注释和字段注释。
-- 兼容性：不新增或删除表、字段、索引、外键和检查约束，不改变字段类型、NULL 约束及默认值；面向当前 MySQL 8.4。
-- 数据处理：本 Migration 不插入、更新、删除或回填任何业务数据。
-- 回滚说明：Down 仅清空本 Migration 添加的表注释和字段注释，不影响表结构及业务数据。
-- 验证 SQL（Up 获得执行批准并完成后，通过 DBHub 只读执行）：
--   SELECT TABLE_NAME, TABLE_COMMENT
--   FROM information_schema.TABLES
--   WHERE TABLE_SCHEMA = DATABASE()
--     AND TABLE_NAME IN ('tenants', 'employees', 'departments', 'roles', 'menus', 'employee_roles', 'role_menus')
--   ORDER BY TABLE_NAME;
--   SELECT TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, COLUMN_COMMENT
--   FROM information_schema.COLUMNS
--   WHERE TABLE_SCHEMA = DATABASE()
--     AND TABLE_NAME IN ('tenants', 'employees', 'departments', 'roles', 'menus', 'employee_roles', 'role_menus')
--   ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- +goose Up

ALTER TABLE `tenants` COMMENT = '租户信息';
ALTER TABLE `tenants`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '租户ID',
  MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '租户名称',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  MODIFY COLUMN `owner_employee_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '租户所有者员工ID';

ALTER TABLE `employees` COMMENT = '后台员工与登录身份';
ALTER TABLE `employees`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '员工ID',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '作用范围：platform平台端，tenant租户端',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '所属租户ID；平台范围为NULL',
  MODIFY COLUMN `department_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '所属部门ID',
  MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '员工姓名',
  MODIFY COLUMN `login_account` VARCHAR(40) NOT NULL COMMENT '后台登录账号',
  MODIFY COLUMN `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  MODIFY COLUMN `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '手机号',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `departments` COMMENT = '部门组织';
ALTER TABLE `departments`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '部门ID',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '作用范围：platform平台端，tenant租户端',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '所属租户ID；平台范围为NULL',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '上级部门ID；顶级部门为NULL',
  MODIFY COLUMN `name` VARCHAR(40) NOT NULL COMMENT '部门名称',
  MODIFY COLUMN `leader_employee_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '部门负责人员工ID',
  MODIFY COLUMN `sort` INT UNSIGNED NOT NULL COMMENT '同级排序值',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用';

ALTER TABLE `roles` COMMENT = '后台角色';
ALTER TABLE `roles`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '作用范围：platform平台端，tenant租户端',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '所属租户ID；平台范围为NULL',
  MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '角色名称',
  MODIFY COLUMN `description` VARCHAR(200) NULL DEFAULT NULL COMMENT '角色描述',
  MODIFY COLUMN `system_key` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL COMMENT '内置角色标识；自定义角色为NULL',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `menus` COMMENT = '后台菜单与操作权限';
ALTER TABLE `menus`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '菜单或权限节点ID',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '父节点ID；根节点为NULL',
  MODIFY COLUMN `name` VARCHAR(40) NOT NULL COMMENT '菜单或权限名称',
  MODIFY COLUMN `node_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '节点类型：directory目录，menu页面，permission操作权限',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '可用范围：platform平台端，tenant租户端',
  MODIFY COLUMN `path` VARCHAR(255) NULL DEFAULT NULL COMMENT '页面静态路由；非页面节点为NULL',
  MODIFY COLUMN `component` VARCHAR(255) NULL DEFAULT NULL COMMENT '前端组件路径元数据；非页面节点为NULL',
  MODIFY COLUMN `icon` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Ant Design图标名称',
  MODIFY COLUMN `permission_code` VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL COMMENT '页面或操作权限标识；目录为NULL',
  MODIFY COLUMN `tenant_assignable` TINYINT UNSIGNED NOT NULL COMMENT '是否允许租户角色分配：1是，0否',
  MODIFY COLUMN `sort` INT UNSIGNED NOT NULL COMMENT '同级排序值',
  MODIFY COLUMN `visible` TINYINT UNSIGNED NOT NULL COMMENT '是否在导航显示：1是，0否',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用';

ALTER TABLE `employee_roles` COMMENT = '员工角色关联';
ALTER TABLE `employee_roles`
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '关联范围：platform平台端，tenant租户端',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '关联租户ID；平台范围为NULL',
  MODIFY COLUMN `employee_id` BIGINT UNSIGNED NOT NULL COMMENT '员工ID',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色ID';

ALTER TABLE `role_menus` COMMENT = '角色菜单权限关联';
ALTER TABLE `role_menus`
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '关联范围：platform平台端，tenant租户端',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '角色所属租户ID；平台范围为NULL',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
  MODIFY COLUMN `menu_id` BIGINT UNSIGNED NOT NULL COMMENT '菜单或权限节点ID';

-- +goose Down

ALTER TABLE `role_menus` COMMENT = '';
ALTER TABLE `role_menus`
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `menu_id` BIGINT UNSIGNED NOT NULL COMMENT '';

ALTER TABLE `employee_roles` COMMENT = '';
ALTER TABLE `employee_roles`
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `employee_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '';

ALTER TABLE `menus` COMMENT = '';
ALTER TABLE `menus`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(40) NOT NULL COMMENT '',
  MODIFY COLUMN `node_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `path` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `component` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `icon` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `permission_code` VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `tenant_assignable` TINYINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `sort` INT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `visible` TINYINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '';

ALTER TABLE `roles` COMMENT = '';
ALTER TABLE `roles`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '',
  MODIFY COLUMN `description` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `system_key` VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE `departments` COMMENT = '';
ALTER TABLE `departments`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(40) NOT NULL COMMENT '',
  MODIFY COLUMN `leader_employee_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `sort` INT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '';

ALTER TABLE `employees` COMMENT = '';
ALTER TABLE `employees`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `scope` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '',
  MODIFY COLUMN `tenant_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `department_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(30) NOT NULL COMMENT '',
  MODIFY COLUMN `login_account` VARCHAR(40) NOT NULL COMMENT '',
  MODIFY COLUMN `password_hash` VARCHAR(255) NOT NULL COMMENT '',
  MODIFY COLUMN `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE `tenants` COMMENT = '';
ALTER TABLE `tenants`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `owner_employee_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '';
